/*
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ComputersListComputerIdAccountinfo struct {
	HARDWARE_ID int32 `json:"HARDWARE_ID,omitempty"`
	TAG string `json:"TAG,omitempty"`
}
