/*
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// In this case batteries and bios are inventory sections defined in Map.pm file
type ComputersList struct {
	ComputerId *ComputersListComputerId `json:"{computer_id},omitempty"`
}
