/*
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SoftwaresListInner struct {
	NAME string `json:"NAME,omitempty"`
	PUBLISHER string `json:"PUBLISHER,omitempty"`
	VERSION string `json:"VERSION,omitempty"`
}
