/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ComputersListComputerId } from './computersListComputerId';

/**
 * In this case batteries and bios are inventory sections defined in Map.pm file
 */
export interface ComputersList { 
    computerId?: ComputersListComputerId;
}