/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComputersListComputerIdBios { 
    ASSETTAG?: string;
    BDATE?: string;
    BMANUFACTURER?: string;
    BVERSION?: string;
    HARDWARE_ID?: number;
    MMANUFACTURER?: string;
    MMODEL?: string;
    MSN?: string;
    SMANUFACTURER?: string;
    SMODEL?: string;
    SSN?: string;
    TYPE?: string;
}