/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IpdiscoverNetdevicesInner { 
    DATE?: Date;
    HARDWARE_ID?: number;
    IP?: string;
    MAC?: string;
    MASK?: string;
    NAME?: string;
    NETID?: string;
    TAG?: string;
}