/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ComputerDetailComputerId

/**
 * 
 * @param Left_Curly_BracketcomputerIdRight_Curly_Bracket 
 */
data class ComputerDetail (

    val Left_Curly_BracketcomputerIdRight_Curly_Bracket: ComputerDetailComputerId? = null
) {
}