/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param aSSETTAG 
 * @param bDATE 
 * @param bMANUFACTURER 
 * @param bVERSION 
 * @param hARDWAREID 
 * @param mMANUFACTURER 
 * @param mMODEL 
 * @param mSN 
 * @param sMANUFACTURER 
 * @param sMODEL 
 * @param sSN 
 * @param tYPE 
 */
data class ComputersListComputerIdBios (

    val aSSETTAG: kotlin.String? = null,
    val bDATE: kotlin.String? = null,
    val bMANUFACTURER: kotlin.String? = null,
    val bVERSION: kotlin.String? = null,
    val hARDWAREID: kotlin.Int? = null,
    val mMANUFACTURER: kotlin.String? = null,
    val mMODEL: kotlin.String? = null,
    val mSN: kotlin.String? = null,
    val sMANUFACTURER: kotlin.String? = null,
    val sMODEL: kotlin.String? = null,
    val sSN: kotlin.String? = null,
    val tYPE: kotlin.String? = null
) {
}