/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ComputersListComputerIdAccountinfo
import io.swagger.client.models.ComputersListComputerIdBios

/**
 * 
 * @param accountinfo 
 * @param batteries 
 * @param bios 
 */
data class ComputersListComputerId (

    val accountinfo: kotlin.Array<ComputersListComputerIdAccountinfo>? = null,
    val batteries: kotlin.Array<kotlin.String>? = null,
    val bios: kotlin.Array<ComputersListComputerIdBios>? = null
) {
}