/**
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param ID  for example: '''13'''
 * @param TABLE_TYPE_NAME  for example: '''snmp_default'''
 * @param TYPE_NAME  for example: '''Default'''
 */
case class SNMPTypeInner (
  ID: Option[Integer] = None,
  TABLE_TYPE_NAME: Option[String] = None,
  TYPE_NAME: Option[String] = None
)

