//
// ComputerDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ComputerDetail: Codable {


    public var computerId: ComputerDetailComputerId?
    public init(computerId: ComputerDetailComputerId? = nil) { 
        self.computerId = computerId
    }
    public enum CodingKeys: String, CodingKey { 
        case computerId = "{computer_id}"
    }

}
