//
// IpdiscoverNetdevicesInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct IpdiscoverNetdevicesInner: Codable {


    public var DATE: Date?

    public var HARDWARE_ID: Int?

    public var IP: String?

    public var MAC: String?

    public var MASK: String?

    public var NAME: String?

    public var NETID: String?

    public var TAG: String?
    public init(DATE: Date? = nil, HARDWARE_ID: Int? = nil, IP: String? = nil, MAC: String? = nil, MASK: String? = nil, NAME: String? = nil, NETID: String? = nil, TAG: String? = nil) { 
        self.DATE = DATE
        self.HARDWARE_ID = HARDWARE_ID
        self.IP = IP
        self.MAC = MAC
        self.MASK = MASK
        self.NAME = NAME
        self.NETID = NETID
        self.TAG = TAG
    }

}
