# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.computers_list_computer_id import ComputersListComputerId  # noqa: F401,E501
from swagger_server import util


class ComputersList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, computer_id: ComputersListComputerId=None):  # noqa: E501
        """ComputersList - a model defined in Swagger

        :param computer_id: The computer_id of this ComputersList.  # noqa: E501
        :type computer_id: ComputersListComputerId
        """
        self.swagger_types = {
            'computer_id': ComputersListComputerId
        }

        self.attribute_map = {
            'computer_id': '{computer_id}'
        }
        self._computer_id = computer_id

    @classmethod
    def from_dict(cls, dikt) -> 'ComputersList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The computersList of this ComputersList.  # noqa: E501
        :rtype: ComputersList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def computer_id(self) -> ComputersListComputerId:
        """Gets the computer_id of this ComputersList.


        :return: The computer_id of this ComputersList.
        :rtype: ComputersListComputerId
        """
        return self._computer_id

    @computer_id.setter
    def computer_id(self, computer_id: ComputersListComputerId):
        """Sets the computer_id of this ComputersList.


        :param computer_id: The computer_id of this ComputersList.
        :type computer_id: ComputersListComputerId
        """

        self._computer_id = computer_id
