# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.computers_list_computer_id_bios import ComputersListComputerIdBios  # noqa: F401,E501
from swagger_server import util


class ComputerDetailComputerId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bios: List[ComputersListComputerIdBios]=None):  # noqa: E501
        """ComputerDetailComputerId - a model defined in Swagger

        :param bios: The bios of this ComputerDetailComputerId.  # noqa: E501
        :type bios: List[ComputersListComputerIdBios]
        """
        self.swagger_types = {
            'bios': List[ComputersListComputerIdBios]
        }

        self.attribute_map = {
            'bios': 'bios'
        }
        self._bios = bios

    @classmethod
    def from_dict(cls, dikt) -> 'ComputerDetailComputerId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The computerDetail_computer_id of this ComputerDetailComputerId.  # noqa: E501
        :rtype: ComputerDetailComputerId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bios(self) -> List[ComputersListComputerIdBios]:
        """Gets the bios of this ComputerDetailComputerId.


        :return: The bios of this ComputerDetailComputerId.
        :rtype: List[ComputersListComputerIdBios]
        """
        return self._bios

    @bios.setter
    def bios(self, bios: List[ComputersListComputerIdBios]):
        """Sets the bios of this ComputerDetailComputerId.


        :param bios: The bios of this ComputerDetailComputerId.
        :type bios: List[ComputersListComputerIdBios]
        """

        self._bios = bios
