# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SNMPDetailInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, default_address_ip: str=None, default_description: str=None, default_gateway: str=None, default_location: str=None, default_mac_address: str=None, default_name: str=None, default_uptime: str=None, id: int=None, lastdate: datetime=None):  # noqa: E501
        """SNMPDetailInner - a model defined in Swagger

        :param default_address_ip: The default_address_ip of this SNMPDetailInner.  # noqa: E501
        :type default_address_ip: str
        :param default_description: The default_description of this SNMPDetailInner.  # noqa: E501
        :type default_description: str
        :param default_gateway: The default_gateway of this SNMPDetailInner.  # noqa: E501
        :type default_gateway: str
        :param default_location: The default_location of this SNMPDetailInner.  # noqa: E501
        :type default_location: str
        :param default_mac_address: The default_mac_address of this SNMPDetailInner.  # noqa: E501
        :type default_mac_address: str
        :param default_name: The default_name of this SNMPDetailInner.  # noqa: E501
        :type default_name: str
        :param default_uptime: The default_uptime of this SNMPDetailInner.  # noqa: E501
        :type default_uptime: str
        :param id: The id of this SNMPDetailInner.  # noqa: E501
        :type id: int
        :param lastdate: The lastdate of this SNMPDetailInner.  # noqa: E501
        :type lastdate: datetime
        """
        self.swagger_types = {
            'default_address_ip': str,
            'default_description': str,
            'default_gateway': str,
            'default_location': str,
            'default_mac_address': str,
            'default_name': str,
            'default_uptime': str,
            'id': int,
            'lastdate': datetime
        }

        self.attribute_map = {
            'default_address_ip': 'DefaultAddressIP',
            'default_description': 'DefaultDescription',
            'default_gateway': 'DefaultGateway',
            'default_location': 'DefaultLocation',
            'default_mac_address': 'DefaultMacAddress',
            'default_name': 'DefaultName',
            'default_uptime': 'DefaultUptime',
            'id': 'ID',
            'lastdate': 'LASTDATE'
        }
        self._default_address_ip = default_address_ip
        self._default_description = default_description
        self._default_gateway = default_gateway
        self._default_location = default_location
        self._default_mac_address = default_mac_address
        self._default_name = default_name
        self._default_uptime = default_uptime
        self._id = id
        self._lastdate = lastdate

    @classmethod
    def from_dict(cls, dikt) -> 'SNMPDetailInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SNMPDetail_inner of this SNMPDetailInner.  # noqa: E501
        :rtype: SNMPDetailInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def default_address_ip(self) -> str:
        """Gets the default_address_ip of this SNMPDetailInner.


        :return: The default_address_ip of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_address_ip

    @default_address_ip.setter
    def default_address_ip(self, default_address_ip: str):
        """Sets the default_address_ip of this SNMPDetailInner.


        :param default_address_ip: The default_address_ip of this SNMPDetailInner.
        :type default_address_ip: str
        """

        self._default_address_ip = default_address_ip

    @property
    def default_description(self) -> str:
        """Gets the default_description of this SNMPDetailInner.


        :return: The default_description of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_description

    @default_description.setter
    def default_description(self, default_description: str):
        """Sets the default_description of this SNMPDetailInner.


        :param default_description: The default_description of this SNMPDetailInner.
        :type default_description: str
        """

        self._default_description = default_description

    @property
    def default_gateway(self) -> str:
        """Gets the default_gateway of this SNMPDetailInner.


        :return: The default_gateway of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_gateway

    @default_gateway.setter
    def default_gateway(self, default_gateway: str):
        """Sets the default_gateway of this SNMPDetailInner.


        :param default_gateway: The default_gateway of this SNMPDetailInner.
        :type default_gateway: str
        """

        self._default_gateway = default_gateway

    @property
    def default_location(self) -> str:
        """Gets the default_location of this SNMPDetailInner.


        :return: The default_location of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_location

    @default_location.setter
    def default_location(self, default_location: str):
        """Sets the default_location of this SNMPDetailInner.


        :param default_location: The default_location of this SNMPDetailInner.
        :type default_location: str
        """

        self._default_location = default_location

    @property
    def default_mac_address(self) -> str:
        """Gets the default_mac_address of this SNMPDetailInner.


        :return: The default_mac_address of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_mac_address

    @default_mac_address.setter
    def default_mac_address(self, default_mac_address: str):
        """Sets the default_mac_address of this SNMPDetailInner.


        :param default_mac_address: The default_mac_address of this SNMPDetailInner.
        :type default_mac_address: str
        """

        self._default_mac_address = default_mac_address

    @property
    def default_name(self) -> str:
        """Gets the default_name of this SNMPDetailInner.


        :return: The default_name of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_name

    @default_name.setter
    def default_name(self, default_name: str):
        """Sets the default_name of this SNMPDetailInner.


        :param default_name: The default_name of this SNMPDetailInner.
        :type default_name: str
        """

        self._default_name = default_name

    @property
    def default_uptime(self) -> str:
        """Gets the default_uptime of this SNMPDetailInner.


        :return: The default_uptime of this SNMPDetailInner.
        :rtype: str
        """
        return self._default_uptime

    @default_uptime.setter
    def default_uptime(self, default_uptime: str):
        """Sets the default_uptime of this SNMPDetailInner.


        :param default_uptime: The default_uptime of this SNMPDetailInner.
        :type default_uptime: str
        """

        self._default_uptime = default_uptime

    @property
    def id(self) -> int:
        """Gets the id of this SNMPDetailInner.


        :return: The id of this SNMPDetailInner.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SNMPDetailInner.


        :param id: The id of this SNMPDetailInner.
        :type id: int
        """

        self._id = id

    @property
    def lastdate(self) -> datetime:
        """Gets the lastdate of this SNMPDetailInner.


        :return: The lastdate of this SNMPDetailInner.
        :rtype: datetime
        """
        return self._lastdate

    @lastdate.setter
    def lastdate(self, lastdate: datetime):
        """Sets the lastdate of this SNMPDetailInner.


        :param lastdate: The lastdate of this SNMPDetailInner.
        :type lastdate: datetime
        """

        self._lastdate = lastdate
