/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// In this case batteries and bios are inventory sections defined in Map.pm file
    /// </summary>
    [DataContract]
        public partial class ComputersList :  IEquatable<ComputersList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComputersList" /> class.
        /// </summary>
        /// <param name="computerId">computerId.</param>
        public ComputersList(ComputersListComputerId computerId = default(ComputersListComputerId))
        {
            this.ComputerId = computerId;
        }
        
        /// <summary>
        /// Gets or Sets ComputerId
        /// </summary>
        [DataMember(Name="{computer_id}", EmitDefaultValue=false)]
        public ComputersListComputerId ComputerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ComputersList {\n");
            sb.Append("  ComputerId: ").Append(ComputerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ComputersList);
        }

        /// <summary>
        /// Returns true if ComputersList instances are equal
        /// </summary>
        /// <param name="input">Instance of ComputersList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ComputersList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ComputerId == input.ComputerId ||
                    (this.ComputerId != null &&
                    this.ComputerId.Equals(input.ComputerId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ComputerId != null)
                    hashCode = hashCode * 59 + this.ComputerId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
