/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ComputersListComputerIdAccountinfo
    /// </summary>
    [DataContract]
        public partial class ComputersListComputerIdAccountinfo :  IEquatable<ComputersListComputerIdAccountinfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ComputersListComputerIdAccountinfo" /> class.
        /// </summary>
        /// <param name="hARDWAREID">hARDWAREID.</param>
        /// <param name="tAG">tAG.</param>
        public ComputersListComputerIdAccountinfo(int? hARDWAREID = default(int?), string tAG = default(string))
        {
            this.HARDWARE_ID = hARDWAREID;
            this.TAG = tAG;
        }
        
        /// <summary>
        /// Gets or Sets HARDWARE_ID
        /// </summary>
        [DataMember(Name="HARDWARE_ID", EmitDefaultValue=false)]
        public int? HARDWARE_ID { get; set; }

        /// <summary>
        /// Gets or Sets TAG
        /// </summary>
        [DataMember(Name="TAG", EmitDefaultValue=false)]
        public string TAG { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ComputersListComputerIdAccountinfo {\n");
            sb.Append("  HARDWARE_ID: ").Append(HARDWARE_ID).Append("\n");
            sb.Append("  TAG: ").Append(TAG).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ComputersListComputerIdAccountinfo);
        }

        /// <summary>
        /// Returns true if ComputersListComputerIdAccountinfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ComputersListComputerIdAccountinfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ComputersListComputerIdAccountinfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HARDWARE_ID == input.HARDWARE_ID ||
                    (this.HARDWARE_ID != null &&
                    this.HARDWARE_ID.Equals(input.HARDWARE_ID))
                ) && 
                (
                    this.TAG == input.TAG ||
                    (this.TAG != null &&
                    this.TAG.Equals(input.TAG))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HARDWARE_ID != null)
                    hashCode = hashCode * 59 + this.HARDWARE_ID.GetHashCode();
                if (this.TAG != null)
                    hashCode = hashCode * 59 + this.TAG.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
