/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// SNMPTypeInner
    /// </summary>
    [DataContract]
        public partial class SNMPTypeInner :  IEquatable<SNMPTypeInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SNMPTypeInner" /> class.
        /// </summary>
        /// <param name="iD">iD.</param>
        /// <param name="tABLETYPENAME">tABLETYPENAME.</param>
        /// <param name="tYPENAME">tYPENAME.</param>
        public SNMPTypeInner(int? iD = default(int?), string tABLETYPENAME = default(string), string tYPENAME = default(string))
        {
            this.ID = iD;
            this.TABLE_TYPE_NAME = tABLETYPENAME;
            this.TYPE_NAME = tYPENAME;
        }
        
        /// <summary>
        /// Gets or Sets ID
        /// </summary>
        [DataMember(Name="ID", EmitDefaultValue=false)]
        public int? ID { get; set; }

        /// <summary>
        /// Gets or Sets TABLE_TYPE_NAME
        /// </summary>
        [DataMember(Name="TABLE_TYPE_NAME", EmitDefaultValue=false)]
        public string TABLE_TYPE_NAME { get; set; }

        /// <summary>
        /// Gets or Sets TYPE_NAME
        /// </summary>
        [DataMember(Name="TYPE_NAME", EmitDefaultValue=false)]
        public string TYPE_NAME { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SNMPTypeInner {\n");
            sb.Append("  ID: ").Append(ID).Append("\n");
            sb.Append("  TABLE_TYPE_NAME: ").Append(TABLE_TYPE_NAME).Append("\n");
            sb.Append("  TYPE_NAME: ").Append(TYPE_NAME).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SNMPTypeInner);
        }

        /// <summary>
        /// Returns true if SNMPTypeInner instances are equal
        /// </summary>
        /// <param name="input">Instance of SNMPTypeInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SNMPTypeInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ID == input.ID ||
                    (this.ID != null &&
                    this.ID.Equals(input.ID))
                ) && 
                (
                    this.TABLE_TYPE_NAME == input.TABLE_TYPE_NAME ||
                    (this.TABLE_TYPE_NAME != null &&
                    this.TABLE_TYPE_NAME.Equals(input.TABLE_TYPE_NAME))
                ) && 
                (
                    this.TYPE_NAME == input.TYPE_NAME ||
                    (this.TYPE_NAME != null &&
                    this.TYPE_NAME.Equals(input.TYPE_NAME))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ID != null)
                    hashCode = hashCode * 59 + this.ID.GetHashCode();
                if (this.TABLE_TYPE_NAME != null)
                    hashCode = hashCode * 59 + this.TABLE_TYPE_NAME.GetHashCode();
                if (this.TYPE_NAME != null)
                    hashCode = hashCode * 59 + this.TYPE_NAME.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
