/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ComputersListComputerIdAccountinfo model module.
 * @module model/ComputersListComputerIdAccountinfo
 * @version 1.0
 */
export class ComputersListComputerIdAccountinfo {
  /**
   * Constructs a new <code>ComputersListComputerIdAccountinfo</code>.
   * @alias module:model/ComputersListComputerIdAccountinfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ComputersListComputerIdAccountinfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComputersListComputerIdAccountinfo} obj Optional instance to populate.
   * @return {module:model/ComputersListComputerIdAccountinfo} The populated <code>ComputersListComputerIdAccountinfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ComputersListComputerIdAccountinfo();
      if (data.hasOwnProperty('HARDWARE_ID'))
        obj.HARDWARE_ID = ApiClient.convertToType(data['HARDWARE_ID'], 'Number');
      if (data.hasOwnProperty('TAG'))
        obj.TAG = ApiClient.convertToType(data['TAG'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} HARDWARE_ID
 */
ComputersListComputerIdAccountinfo.prototype.HARDWARE_ID = undefined;

/**
 * @member {String} TAG
 */
ComputersListComputerIdAccountinfo.prototype.TAG = undefined;

