/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The IpdiscoverListInner model module.
 * @module model/IpdiscoverListInner
 * @version 1.0
 */
export class IpdiscoverListInner {
  /**
   * Constructs a new <code>IpdiscoverListInner</code>.
   * @alias module:model/IpdiscoverListInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpdiscoverListInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpdiscoverListInner} obj Optional instance to populate.
   * @return {module:model/IpdiscoverListInner} The populated <code>IpdiscoverListInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpdiscoverListInner();
      if (data.hasOwnProperty('NETID'))
        obj.NETID = ApiClient.convertToType(data['NETID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} NETID
 */
IpdiscoverListInner.prototype.NETID = undefined;

