/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IpdiscoverListInner} from './IpdiscoverListInner';

/**
 * The IpdiscoverList model module.
 * @module model/IpdiscoverList
 * @version 1.0
 */
export class IpdiscoverList extends Array {
  /**
   * Constructs a new <code>IpdiscoverList</code>.
   * @alias module:model/IpdiscoverList
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>IpdiscoverList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IpdiscoverList} obj Optional instance to populate.
   * @return {module:model/IpdiscoverList} The populated <code>IpdiscoverList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpdiscoverList();
      ApiClient.constructFromObject(data, obj, 'IpdiscoverListInner');
    }
    return obj;
  }
}
