/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ListOfID model module.
 * @module model/ListOfID
 * @version 1.0
 */
export class ListOfID {
  /**
   * Constructs a new <code>ListOfID</code>.
   * @alias module:model/ListOfID
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListOfID</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListOfID} obj Optional instance to populate.
   * @return {module:model/ListOfID} The populated <code>ListOfID</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListOfID();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} ID
 */
ListOfID.prototype.ID = undefined;

