/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SNMPTypeInner} from './SNMPTypeInner';

/**
 * The SNMPType model module.
 * @module model/SNMPType
 * @version 1.0
 */
export class SNMPType extends Array {
  /**
   * Constructs a new <code>SNMPType</code>.
   * @alias module:model/SNMPType
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>SNMPType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SNMPType} obj Optional instance to populate.
   * @return {module:model/SNMPType} The populated <code>SNMPType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SNMPType();
      ApiClient.constructFromObject(data, obj, 'SNMPTypeInner');
    }
    return obj;
  }
}
