/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SNMPTypeInner model module.
 * @module model/SNMPTypeInner
 * @version 1.0
 */
export class SNMPTypeInner {
  /**
   * Constructs a new <code>SNMPTypeInner</code>.
   * @alias module:model/SNMPTypeInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SNMPTypeInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SNMPTypeInner} obj Optional instance to populate.
   * @return {module:model/SNMPTypeInner} The populated <code>SNMPTypeInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SNMPTypeInner();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
      if (data.hasOwnProperty('TABLE_TYPE_NAME'))
        obj.TABLE_TYPE_NAME = ApiClient.convertToType(data['TABLE_TYPE_NAME'], 'String');
      if (data.hasOwnProperty('TYPE_NAME'))
        obj.TYPE_NAME = ApiClient.convertToType(data['TYPE_NAME'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} ID
 */
SNMPTypeInner.prototype.ID = undefined;

/**
 * @member {String} TABLE_TYPE_NAME
 */
SNMPTypeInner.prototype.TABLE_TYPE_NAME = undefined;

/**
 * @member {String} TYPE_NAME
 */
SNMPTypeInner.prototype.TYPE_NAME = undefined;

