# coding: utf-8

"""
    OCS Inventory Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.computers_list_computer_id_bios import ComputersListComputerIdBios  # noqa: E501
from swagger_client.rest import ApiException


class TestComputersListComputerIdBios(unittest.TestCase):
    """ComputersListComputerIdBios unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputersListComputerIdBios(self):
        """Test ComputersListComputerIdBios"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.computers_list_computer_id_bios.ComputersListComputerIdBios()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
