# coding: utf-8

"""
    OCS Inventory Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ipdiscover_list_inner import IpdiscoverListInner  # noqa: E501
from swagger_client.rest import ApiException


class TestIpdiscoverListInner(unittest.TestCase):
    """IpdiscoverListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIpdiscoverListInner(self):
        """Test IpdiscoverListInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ipdiscover_list_inner.IpdiscoverListInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
