# coding: utf-8

"""
    OCS Inventory Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.snmp_detail import SNMPDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestSNMPDetail(unittest.TestCase):
    """SNMPDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSNMPDetail(self):
        """Test SNMPDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.snmp_detail.SNMPDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
