# coding: utf-8

"""
    OCS Inventory Rest API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_computer_id_get(self):
        """Test case for computer_id_get

        Get a computer by its ID  # noqa: E501
        """
        pass

    def test_computer_id_sections_get(self):
        """Test case for computer_id_sections_get

        Get sections informations of a specific computer  # noqa: E501
        """
        pass

    def test_computers_get(self):
        """Test case for computers_get

        Get a list of computers with its detail  # noqa: E501
        """
        pass

    def test_computers_lastupdate_timestamp_get(self):
        """Test case for computers_lastupdate_timestamp_get

        Get a ID list of computers update during the provided timestamp  # noqa: E501
        """
        pass

    def test_computers_list_id_get(self):
        """Test case for computers_list_id_get

        Get a ID list of all computers in the OCS database  # noqa: E501
        """
        pass

    def test_ipdiscover_get(self):
        """Test case for ipdiscover_get

        List IPDiscover network list  # noqa: E501
        """
        pass

    def test_ipdiscover_network_netid_get(self):
        """Test case for ipdiscover_network_netid_get

        Get list of network devices scanned on one network  # noqa: E501
        """
        pass

    def test_snmp_snmp_type_get(self):
        """Test case for snmp_snmp_type_get

        Get snmp device list of a specific snmp type  # noqa: E501
        """
        pass

    def test_snmp_snmp_type_id_get(self):
        """Test case for snmp_snmp_type_id_get

        Get a device from a snmp type with its ID  # noqa: E501
        """
        pass

    def test_snmps_type_list_get(self):
        """Test case for snmps_type_list_get

        Get a SNMP type list  # noqa: E501
        """
        pass

    def test_softwares_get(self):
        """Test case for softwares_get

        Get software list from database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
