/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ComputerDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComputerDetailTests
    {
        // TODO uncomment below to declare an instance variable for ComputerDetail
        //private ComputerDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComputerDetail
            //instance = new ComputerDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComputerDetail
        /// </summary>
        [Test]
        public void ComputerDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComputerDetail
            //Assert.IsInstanceOfType<ComputerDetail> (instance, "variable 'instance' is a ComputerDetail");
        }


        /// <summary>
        /// Test the property 'ComputerId'
        /// </summary>
        [Test]
        public void ComputerIdTest()
        {
            // TODO unit test for the property 'ComputerId'
        }

    }

}
