/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ComputersListComputerIdBios
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ComputersListComputerIdBiosTests
    {
        // TODO uncomment below to declare an instance variable for ComputersListComputerIdBios
        //private ComputersListComputerIdBios instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ComputersListComputerIdBios
            //instance = new ComputersListComputerIdBios();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ComputersListComputerIdBios
        /// </summary>
        [Test]
        public void ComputersListComputerIdBiosInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ComputersListComputerIdBios
            //Assert.IsInstanceOfType<ComputersListComputerIdBios> (instance, "variable 'instance' is a ComputersListComputerIdBios");
        }


        /// <summary>
        /// Test the property 'ASSETTAG'
        /// </summary>
        [Test]
        public void ASSETTAGTest()
        {
            // TODO unit test for the property 'ASSETTAG'
        }
        /// <summary>
        /// Test the property 'BDATE'
        /// </summary>
        [Test]
        public void BDATETest()
        {
            // TODO unit test for the property 'BDATE'
        }
        /// <summary>
        /// Test the property 'BMANUFACTURER'
        /// </summary>
        [Test]
        public void BMANUFACTURERTest()
        {
            // TODO unit test for the property 'BMANUFACTURER'
        }
        /// <summary>
        /// Test the property 'BVERSION'
        /// </summary>
        [Test]
        public void BVERSIONTest()
        {
            // TODO unit test for the property 'BVERSION'
        }
        /// <summary>
        /// Test the property 'HARDWARE_ID'
        /// </summary>
        [Test]
        public void HARDWARE_IDTest()
        {
            // TODO unit test for the property 'HARDWARE_ID'
        }
        /// <summary>
        /// Test the property 'MMANUFACTURER'
        /// </summary>
        [Test]
        public void MMANUFACTURERTest()
        {
            // TODO unit test for the property 'MMANUFACTURER'
        }
        /// <summary>
        /// Test the property 'MMODEL'
        /// </summary>
        [Test]
        public void MMODELTest()
        {
            // TODO unit test for the property 'MMODEL'
        }
        /// <summary>
        /// Test the property 'MSN'
        /// </summary>
        [Test]
        public void MSNTest()
        {
            // TODO unit test for the property 'MSN'
        }
        /// <summary>
        /// Test the property 'SMANUFACTURER'
        /// </summary>
        [Test]
        public void SMANUFACTURERTest()
        {
            // TODO unit test for the property 'SMANUFACTURER'
        }
        /// <summary>
        /// Test the property 'SMODEL'
        /// </summary>
        [Test]
        public void SMODELTest()
        {
            // TODO unit test for the property 'SMODEL'
        }
        /// <summary>
        /// Test the property 'SSN'
        /// </summary>
        [Test]
        public void SSNTest()
        {
            // TODO unit test for the property 'SSN'
        }
        /// <summary>
        /// Test the property 'TYPE'
        /// </summary>
        [Test]
        public void TYPETest()
        {
            // TODO unit test for the property 'TYPE'
        }

    }

}
