/* 
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IpdiscoverNetdevicesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IpdiscoverNetdevicesInnerTests
    {
        // TODO uncomment below to declare an instance variable for IpdiscoverNetdevicesInner
        //private IpdiscoverNetdevicesInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IpdiscoverNetdevicesInner
            //instance = new IpdiscoverNetdevicesInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IpdiscoverNetdevicesInner
        /// </summary>
        [Test]
        public void IpdiscoverNetdevicesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IpdiscoverNetdevicesInner
            //Assert.IsInstanceOfType<IpdiscoverNetdevicesInner> (instance, "variable 'instance' is a IpdiscoverNetdevicesInner");
        }


        /// <summary>
        /// Test the property 'DATE'
        /// </summary>
        [Test]
        public void DATETest()
        {
            // TODO unit test for the property 'DATE'
        }
        /// <summary>
        /// Test the property 'HARDWARE_ID'
        /// </summary>
        [Test]
        public void HARDWARE_IDTest()
        {
            // TODO unit test for the property 'HARDWARE_ID'
        }
        /// <summary>
        /// Test the property 'IP'
        /// </summary>
        [Test]
        public void IPTest()
        {
            // TODO unit test for the property 'IP'
        }
        /// <summary>
        /// Test the property 'MAC'
        /// </summary>
        [Test]
        public void MACTest()
        {
            // TODO unit test for the property 'MAC'
        }
        /// <summary>
        /// Test the property 'MASK'
        /// </summary>
        [Test]
        public void MASKTest()
        {
            // TODO unit test for the property 'MASK'
        }
        /// <summary>
        /// Test the property 'NAME'
        /// </summary>
        [Test]
        public void NAMETest()
        {
            // TODO unit test for the property 'NAME'
        }
        /// <summary>
        /// Test the property 'NETID'
        /// </summary>
        [Test]
        public void NETIDTest()
        {
            // TODO unit test for the property 'NETID'
        }
        /// <summary>
        /// Test the property 'TAG'
        /// </summary>
        [Test]
        public void TAGTest()
        {
            // TODO unit test for the property 'TAG'
        }

    }

}
