/*
 * OCS Inventory Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OcsInventoryRestApi);
  }
}(this, function(expect, OcsInventoryRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SoftwaresListInner', function() {
      beforeEach(function() {
        instance = new OcsInventoryRestApi.SoftwaresListInner();
      });

      it('should create an instance of SoftwaresListInner', function() {
        // TODO: update the code to test SoftwaresListInner
        expect(instance).to.be.a(OcsInventoryRestApi.SoftwaresListInner);
      });

      it('should have the property NAME (base name: "NAME")', function() {
        // TODO: update the code to test the property NAME
        expect(instance).to.have.property('NAME');
        // expect(instance.NAME).to.be(expectedValueLiteral);
      });

      it('should have the property PUBLISHER (base name: "PUBLISHER")', function() {
        // TODO: update the code to test the property PUBLISHER
        expect(instance).to.have.property('PUBLISHER');
        // expect(instance.PUBLISHER).to.be(expectedValueLiteral);
      });

      it('should have the property VERSION (base name: "VERSION")', function() {
        // TODO: update the code to test the property VERSION
        expect(instance).to.have.property('VERSION');
        // expect(instance.VERSION).to.be(expectedValueLiteral);
      });

    });
  });

}));
