//
// ComputersListComputerIdBios.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ComputersListComputerIdBios: JSONEncodable {
    public var ASSETTAG: String?
    public var BDATE: String?
    public var BMANUFACTURER: String?
    public var BVERSION: String?
    public var HARDWARE_ID: Int32?
    public var MMANUFACTURER: String?
    public var MMODEL: String?
    public var MSN: String?
    public var SMANUFACTURER: String?
    public var SMODEL: String?
    public var SSN: String?
    public var TYPE: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["ASSETTAG"] = self.ASSETTAG
        nillableDictionary["BDATE"] = self.BDATE
        nillableDictionary["BMANUFACTURER"] = self.BMANUFACTURER
        nillableDictionary["BVERSION"] = self.BVERSION
        nillableDictionary["HARDWARE_ID"] = self.HARDWARE_ID?.encodeToJSON()
        nillableDictionary["MMANUFACTURER"] = self.MMANUFACTURER
        nillableDictionary["MMODEL"] = self.MMODEL
        nillableDictionary["MSN"] = self.MSN
        nillableDictionary["SMANUFACTURER"] = self.SMANUFACTURER
        nillableDictionary["SMODEL"] = self.SMODEL
        nillableDictionary["SSN"] = self.SSN
        nillableDictionary["TYPE"] = self.TYPE

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
