//
// ComputersList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** In this case batteries and bios are inventory sections defined in Map.pm file */
open class ComputersList: JSONEncodable {
    public var computerId: ComputersListComputerId?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["{computer_id}"] = self.computerId?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
