//
// SNMPTypeInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SNMPTypeInner: JSONEncodable {
    public var ID: Int32?
    public var TABLE_TYPE_NAME: String?
    public var TYPE_NAME: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["ID"] = self.ID?.encodeToJSON()
        nillableDictionary["TABLE_TYPE_NAME"] = self.TABLE_TYPE_NAME
        nillableDictionary["TYPE_NAME"] = self.TYPE_NAME

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
