<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OCS Inventory Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for computerIdGet
     *
     * Get a computer by its ID.
     *
     */
    public function testComputerIdGet()
    {
    }

    /**
     * Test case for computerIdSectionsGet
     *
     * Get sections informations of a specific computer.
     *
     */
    public function testComputerIdSectionsGet()
    {
    }

    /**
     * Test case for computersGet
     *
     * Get a list of computers with its detail.
     *
     */
    public function testComputersGet()
    {
    }

    /**
     * Test case for computersLastupdateTimestampGet
     *
     * Get a ID list of computers update during the provided timestamp.
     *
     */
    public function testComputersLastupdateTimestampGet()
    {
    }

    /**
     * Test case for computersListIDGet
     *
     * Get a ID list of all computers in the OCS database.
     *
     */
    public function testComputersListIDGet()
    {
    }

    /**
     * Test case for ipdiscoverGet
     *
     * List IPDiscover network list.
     *
     */
    public function testIpdiscoverGet()
    {
    }

    /**
     * Test case for ipdiscoverNetworkNetidGet
     *
     * Get list of network devices scanned on one network.
     *
     */
    public function testIpdiscoverNetworkNetidGet()
    {
    }

    /**
     * Test case for snmpSnmpTypeGet
     *
     * Get snmp device list of a specific snmp type.
     *
     */
    public function testSnmpSnmpTypeGet()
    {
    }

    /**
     * Test case for snmpSnmpTypeIdGet
     *
     * Get a device from a snmp type with its ID.
     *
     */
    public function testSnmpSnmpTypeIdGet()
    {
    }

    /**
     * Test case for snmpsTypeListGet
     *
     * Get a SNMP type list.
     *
     */
    public function testSnmpsTypeListGet()
    {
    }

    /**
     * Test case for softwaresGet
     *
     * Get software list from database.
     *
     */
    public function testSoftwaresGet()
    {
    }
}
