//
// ComputersListComputerIdAccountinfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComputersListComputerIdAccountinfo: Codable {

    public var HARDWARE_ID: Int?
    public var TAG: String?

    public init(HARDWARE_ID: Int? = nil, TAG: String? = nil) {
        self.HARDWARE_ID = HARDWARE_ID
        self.TAG = TAG
    }


}
