//
// ComputersListComputerId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ComputersListComputerId: Codable {

    public var accountinfo: [ComputersListComputerIdAccountinfo]?
    public var batteries: [String]?
    public var bios: [ComputersListComputerIdBios]?

    public init(accountinfo: [ComputersListComputerIdAccountinfo]? = nil, batteries: [String]? = nil, bios: [ComputersListComputerIdBios]? = nil) {
        self.accountinfo = accountinfo
        self.batteries = batteries
        self.bios = bios
    }


}
