//
// IpdiscoverListInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IpdiscoverListInner: Codable {

    public var NETID: String?

    public init(NETID: String? = nil) {
        self.NETID = NETID
    }


}
