//
// SNMPTypeInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SNMPTypeInner: Codable {

    public var ID: Int?
    public var TABLE_TYPE_NAME: String?
    public var TYPE_NAME: String?

    public init(ID: Int? = nil, TABLE_TYPE_NAME: String? = nil, TYPE_NAME: String? = nil) {
        self.ID = ID
        self.TABLE_TYPE_NAME = TABLE_TYPE_NAME
        self.TYPE_NAME = TYPE_NAME
    }


}
