//
// SNMPDetailInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SNMPDetailInner: Codable {

    public var defaultAddressIP: String?
    public var defaultDescription: String?
    public var defaultGateway: String?
    public var defaultLocation: String?
    public var defaultMacAddress: String?
    public var defaultName: String?
    public var defaultUptime: String?
    public var ID: Int?
    public var LASTDATE: Date?

    public init(defaultAddressIP: String? = nil, defaultDescription: String? = nil, defaultGateway: String? = nil, defaultLocation: String? = nil, defaultMacAddress: String? = nil, defaultName: String? = nil, defaultUptime: String? = nil, ID: Int? = nil, LASTDATE: Date? = nil) {
        self.defaultAddressIP = defaultAddressIP
        self.defaultDescription = defaultDescription
        self.defaultGateway = defaultGateway
        self.defaultLocation = defaultLocation
        self.defaultMacAddress = defaultMacAddress
        self.defaultName = defaultName
        self.defaultUptime = defaultUptime
        self.ID = ID
        self.LASTDATE = LASTDATE
    }

    public enum CodingKeys: String, CodingKey { 
        case defaultAddressIP = "DefaultAddressIP"
        case defaultDescription = "DefaultDescription"
        case defaultGateway = "DefaultGateway"
        case defaultLocation = "DefaultLocation"
        case defaultMacAddress = "DefaultMacAddress"
        case defaultName = "DefaultName"
        case defaultUptime = "DefaultUptime"
        case ID
        case LASTDATE
    }

}
